### ISSUE TITLE
Thank you! Awesome lists

### ISSUE THREAD

**Issue by itsvrl** [natarii/vrchat-domain-blocklist#2]
Thank you @natarii taking your time creating this list!

I own a OpenWRT router with Adguard Home on it allowing for network-wide ad-blocking. Can you make a list with just the domain names, so I can apply this list  to my ad-blocking router or accept the pull-request?

I've create a PR #1 so you can consider 🙂

**Comment by natarii** [comment]
Thanks for your feedback. I'll close this since I've replied in your PR.
